const productsArray = [
    {
        name: "Celestial 3 tent",
        description: "Offering quick, intuitive setup, outstanding weather protection and a plethora of features at a great price, the award-winning Mountainsmith Celestial 3-person tent won't disappoint.",
        price: 16473,
        quantity: 25,
        category: "camp hike",
        brand: "Mountainsmith",
        imageUrl: "https://www.rei.com/media/b6c67161-91ee-4268-adcf-2a09d4736a2c.jpg"
    },
    {
        name: "Camp Creek 6 Two-room Tent",
        description: "A home away from home when camping with a group of family or friends, the 6-person ALPS Mountaineering Camp Creek Two-Room tent offers cabin-style comfort with a 7 ft. tall peak height.",
        price: 29973,
        quantity: 25,
        category: "camp hike",
        brand: "ALPS Mountaineering",
        imageUrl: "https://www.rei.com/media/8588c8be-0a8a-4242-8e8f-50d9f6764e21.jpg"
    },
    {
        name: "Aurora 2p Tent with Footprint",
        description: "With angular patterning reminiscent of mountainscapes, the NEMO Aurora 2P tent with footprint is a versatile and inviting home for adventure—ideal for car camping but light enough for backpacking.",
        price: 27995,
        quantity: 25,
        category: "camp hike",
        brand: "NEMO",
        imageUrl: "https://www.rei.com/media/58492632-3e5e-4038-846a-d5e73e378fd1.jpg"
    },
    {
        name: "Discovery 2 Tent",
        description: "Put the week's adulting aside and get outdoors with the Kelty Discovery 2-person tent, a spacious design with room for 2 that sets up easily and keeps you protected with a waterproof fly.",
        price: 7995,
        quantity: 25,
        category: "camp hike",
        brand: "Kelty",
        imageUrl: "https://www.rei.com/media/ab536e24-68a6-4151-a1a1-64dfcfb9d6da.jpg"
    },
    {
        name: "Limelight 3p Tent with Footprint",
        description: "With ample overhead space, the Marmot Limelight 3P tent with footprint ensures you'll strike the perfect balance between 3-season protection and roomy comfort on your next night in nature.",
        price: 32200,
        quantity: 25,
        category: "camp hike",
        brand: "Marmot",
        imageUrl: "https://www.rei.com/media/b2a3feff-f721-45b3-b441-d8eb4799136d.jpg"
    },
    {
        name: "Deuter Aircontact Lite 65 + 10 Pack - Men's",
        description: "The Deuter Aircontact Lite 65 + 10 pack balances reliable comfort, lightweight construction and ventilation. Vari-Quick back length adjustment and loads of features make it a do-it-all trekking pack.",
        price: 15393,
        quantity: 25,
        category: "camp hike",// "men",
        brand: "Deuter",
        imageUrl: "https://www.rei.com/media/7381729b-6f2c-4eae-ae4f-1a461b571ad3.jpg"
    },
    {
        name: "Deuter Aircontact Lite 50 + 10 Pack - Men's",
        description: "The perfect balance between reliable comfort, lightweight construction and ventilation, the Deuter Aircontact Lite 50 + 10 pack is durable and boasts effective load transfer features.",
        price: 13993,
        quantity: 25,
        category: "camp hike",// "men",
        brand: "Deuter",
        imageUrl: "https://www.rei.com/media/c5dd81e7-d1a5-41e6-800f-8f3bb8bb58b4.jpg"
    }, 
    {
        name: "Terra 55 Pack - Kids'",
        description: "A go-to pack for intrepid young explorers, The North Face Terra 55 kids' pack has a comfy, easy-to-adjust OPTIFIT™ suspension and deeply considered features they'll use every time they hit the trail.",
        price: 11973,
        quantity: 25,
        category: "camp hike",// "kids",
        brand: "The North Face",
        imageUrl: "https://www.rei.com/media/b8e0a02c-5716-41db-9ab8-5172b19b485a.jpg"
    }, 
    {
        name: "Rook 50 Pack - Women's",
        description: "Dreaming of days spent on the trail? The men's Osprey Rook 50 pack helps you get there. Its ventilated design, easy adjustment and large capacity keep you moving in comfort on long treks.",
        price: 15500,
        quantity: 25,
        category: "camp hike",// "women",
        brand: "Osprey",
        imageUrl: "https://www.rei.com/media/13190756-5b7a-46ab-8412-2d1802235f51?size=784x588"
    }, 
    {
        name: "Aether 65 Pack - women's",
        description: "Built to comfortably haul heavy loads for the weekend or for a week, the men's Osprey Aether 65 pack features a highly customizable fit for a variety of body shapes and sizes.",
        price: 29000,
        quantity: 25,
        category: "camp hike",// "women",
        brand: "Osprey",
        imageUrl: "https://www.rei.com/media/012f78cc-b7d0-48ec-9bb6-8f20281193b2?size=784x588"
    }, 
    {
        name: "Kelty Cosmic 20 Sleeping Bag - Men's",
        description: "A 3-season superstar for nights when temps dip to subfreezing, the men's Kelty Cosmic 20 sleeping bag's thermally efficient trapezoidal baffle construction and 550-fill-power down keep you warm.",
        price: 15995,
        quantity: 25,
        category: "camp hike",
        brand: "Kelty",
        imageUrl: "https://www.rei.com/media/d273cf87-2eca-493f-80dd-7b764471eabf.jpg"
    }, 
    {
        name: "NEMO Disco 15 Sleeping Bag - Men's",
        description: "Unlike most mummy bags, the men's 3-season NEMO Disco 15 sleeping bag is designed to let you sleep on your side in plush comfort anywhere you set up camp. Side sleepers, rejoice!",
        price: 29999,
        quantity: 25,
        category: "camp hike",
        brand: "NEMO",
        imageUrl: "https://www.rei.com/media/c56aec78-bb38-4fba-b11c-54fbb2300294.jpg"
    }, 
    {
        name: "NEMO Forte 35 Sleeping Bag - Women's",
        description: "Classic mummy-bag design isn't ideal for the 70% of people who sleep on their side. The women's NEMO Forte 35 sleeping bag adds room at the elbows and knees for 3-season, side-sleeping comfort.",
        price: 26599,
        quantity: 25,
        category: "camp hike",
        brand: "NEMO",
        imageUrl: "https://www.rei.com/media/1da0889c-dd2c-485e-9907-73bcc443ed13.jpg"
    }, 
    {
        name: "NEMO Disco 15 Sleeping Bag - Women's",
        description: "Side sleepers, rejoice! Unlike most mummy bags, the women's 3-season NEMO Disco 15 sleeping bag is designed to let you sleep on your side in plush comfort anywhere you set up camp.",
        price: 19998,
        quantity: 25,
        category: "camp hike",
        brand: "NEMO",
        imageUrl: "https://www.rei.com/media/b6f38803-4b3f-46a7-bf65-d195e2fc71bc.jpg"
    }, 
    {
        name: "Selk'Bag Recycled Wearable Sleeping Bag - Kids'",
        description: "description",
        price: 8995,
        quantity: 25,
        category: "camp hike",
        brand: "Selk'Bag",
        imageUrl: "https://www.rei.com/media/1de9040a-4575-400f-bb64-b20f19c6e7b5?size=784x588"
    }, 
    {
        name: "Spot 350 Headlamp",
        description: "Now housed in a smaller, lower-profile design with a wide array of brightness modes, the Black Diamond Spot 350 headlamp ensures you'll see what's ahead or right in front even in the darkest hours.",
        price: 3995,
        quantity: 25,
        category: "camp hike",
        brand: "Black Diamond",
        imageUrl: "https://www.rei.com/media/59691673-2899-4dd9-8ef5-ad951d481b53.jpg"
    }, 
    {
        name: "Actik Core Headlamp",
        description: "A rechargeable, multi-beam headlamp, the Petzl Actik Core offers 450 lumens of power to light the way during dynamic outdoor activities like running, hiking and backpacking.",
        price: 6995,
        quantity: 25,
        category: "camp hike",
        brand: "Petzl",
        imageUrl: "https://www.rei.com/media/1aaedbbf-4d36-4e24-85bf-bed97e5d5c12.jpg"
    }, 
    {
        name: "Tikka Headlamp",
        description: "Prepping dinner at the campsite or heading out for a predawn hike gets a little easier with the Petzl Tikka headlamp. Its 300-lumen flood beam provides ample lighting for proximity and some movement.",
        price: 2995,
        quantity: 25,
        category: "camp hike",
        brand: "Petzl",
        imageUrl: "https://www.rei.com/media/7eb2d077-ecd4-4cea-9ed8-e0fec161a32b.jpg"
    }, 
    {
        name: "LuminAID PackLite Max 2-in-1 Power Lantern",
        description: "Light up your campsite and provide a backup battery charge to your devices when you are off the grid with the LuminAID PackLite Max 2-in-1 power lantern.",
        price: 4995,
        quantity: 25,
        category: "camp hike",
        brand: "LuminAID",
        imageUrl: "https://www.rei.com/media/3e3fc8a4-7834-4761-aec8-7c5ad185aedf.jpg"
    }, 
    {
        name: "Black Diamond Moji Lantern",
        description: "Simple, bright and compact, the Moji lantern features durable construction and a powerful 100 lumens of light in a remarkably light 3-ounce frame for incredible visibility at backcountry campsites.",
        price: 2495,
        quantity: 25,
        category: "camp hike",
        brand: "Black Diamond",
        imageUrl: "https://www.rei.com/media/a23f6c70-c6ff-4f74-9a16-569a585711ed.jpg"
    }, 
    {
        name: "Tri-Leg Stool - Clay/Apricot",
        description: "Perfect to bring along when space is limited and weight is a factor, the ALPS Mountaineering Tri-Leg stool makes it easy to snag a spot by the campfire or on the soccer field sidelines.",
        price: 1873,
        quantity: 25,
        category: "camp hike",
        brand: "ALPS Mountaineering",
        imageUrl: "https://www.rei.com/media/e2418141-1928-44d4-9caa-99356e011cb7.jpg"
    }, 
    {
        name: "Helinox Chair Zero",
        description: "The Helinox Chair Zero is a lightweight and comfortable, four-legged camp chair that packs down to the width of a standard 32 oz. water bottle and weighs just a single pound.",
        price: 12995,
        quantity: 25,
        category: "camp hike",
        brand: "Helinox",
        imageUrl: "https://www.rei.com/media/dc47d9eb-d3d8-4c1f-93e9-9e8a33d70f84.jpg"
    }, 
    {
        name: "Timberline Camp Chair",
        description: "Sit back and relax with a low-to-the-ground seat position that's perfect for chilling by the fire. The Klymit Timberline camp chair is easy to use and folds down small for travel and storage.",
        price: 4473,
        quantity: 25,
        category: "camp hike",
        brand: "Klymit",
        imageUrl: "https://www.rei.com/media/a206c2c3-23e9-43c0-b1a8-dea754fbf4cc.jpg"
    }, 
    {
        name: "GCI Outdoor Kickback Rocker Chair",
        description: "Supplying copious comfort for its midsize stature, the light and compact GCI Outdoor Kickback Rocker chair sits slightly lower than standard chairs, but higher than low-to-the-ground designs.",
        price: 6500,
        quantity: 25,
        category: "camp hike",
        brand: "GCI Outdoor",
        imageUrl: "https://www.rei.com/media/42ee18df-a88c-4100-a4b6-7d65d0744ad5.jpg"
    }, 
    {
        name: "Kelty Low Loveseat",
        description: "Cuddle up with your partner or best pal in the Kelty Low loveseat. Its relaxed, low-profile, reclined design means you won't be towering over the campfire or blocking anyone's view of the stage.",
        price: 13995,
        quantity: 25,
        category: "camp hike",
        brand: "Kelty",
        imageUrl: "https://www.rei.com/media/985fe6c3-c36e-45ed-b2a4-3d86acff75c4.jpg"
    }, 
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    }, 
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    }, 
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    }, 
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    }, 
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },    
    {
        name: "name",
        description: "description",
        price: 99999,
        quantity: 25,
        category: "none",
        brand: "brand",
    },  
]


module.exports = productsArray;